### ISSUE TITLE
Does not generate the correct MANIFEST [PAXURL-77]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.url#120]
**[Charles Moulliard](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:3d5df8f3-265c-4a4f-8504-00d641064789)** created **[PAXURL-77](https://ops4j1.jira.com/browse/PAXURL-77)** 

Here is the config of my bnd + command used :

```
karaf@root> D:\Dvlpt\Java\workspace\apache-smx4-source\apache-servicemix-4.1.0-SNAPSHOT\bin>servicemix.bat
 ____                  _          __  __ _
/ ___|  ___ _ ____   _(_) ___ ___|  \/  (_)_  __
\___ \ / _ \ '__\ \ / / |/ __/ _ \ |\/| | \ \/ /
 ___) |  __/ |   \ V /| | (_|  __/ |  | | |>  <
|____/ \___|_|    \_/ |_|\___\___|_|  |_|_/_/\_\

  Apache ServiceMix (4.1.0-SNAPSHOT)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.

karaf@root> osgi:install -s warref:file:///d:/temp/camel-web.bnd
Exception in thread "Thread-19" java.lang.RuntimeException: Bundle cannot be generated
        at org.ops4j.pax.swissbox.bnd.BndUtils$1.run(BndUtils.java:171)
Caused by: java.io.IOException: Pipe closed
        at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:244)
        at java.io.PipedInputStream.receive(PipedInputStream.java:185)
        at java.io.PipedOutputStream.write(PipedOutputStream.java:105)
        at java.util.zip.ZipOutputStream.writeInt(ZipOutputStream.java:447)
        at java.util.zip.ZipOutputStream.writeCEN(ZipOutputStream.java:398)
        at java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:309)
        at aQute.lib.osgi.Jar.write(Jar.java:214)
        at org.ops4j.pax.swissbox.bnd.BndUtils$1.run(BndUtils.java:167)
Bundle ID: 104
```

```java
WAR-URL:\
  war:mvn:org.apache.camel/camel-web/2.1.0/war

Bundle-SymbolicName:\
 camel.webconsole

Bundle-Version:\
  2.1.0

Export-Package:\
  !*

Bundle-Classpath:\
   .,\
   WEB-INF/classes,\
   WEB-INF/tags/api

Webapp-Context:\
  activemqweb

Import-Package:\
  javax.*; resolution:=optional,\
  com.sun.jersey.spi.spring.container.servlet.*; resolution:=optional,\
  !*
```

Result of what PAX generates :

```java
Manifest-Version: 1.0
Bundle-ClassPath: .,WEB-INF/classes,WEB-INF/lib/activation-1.1.jar,WEB
 -INF/lib/ant-1.7.1.jar,WEB-INF/lib/ant-launcher-1.7.1.jar,WEB-INF/lib
 /aopalliance-1.0.jar,WEB-INF/lib/asm-3.1.jar,WEB-INF/lib/camel-core-2
 .1.0.jar,WEB-INF/lib/camel-groovy-2.1.0.jar,WEB-INF/lib/camel-ruby-2.
 1.0.jar,WEB-INF/lib/camel-spring-2.1.0.jar,WEB-INF/lib/commons-loggin
 g-api-1.1.jar,WEB-INF/lib/commons-management-1.0.jar,WEB-INF/lib/groo
 vy-all-1.6.3.jar,WEB-INF/lib/jdom-1.0.jar,WEB-INF/lib/jline-0.9.94.ja
 r,WEB-INF/lib/jruby-1.2.0.jar,WEB-INF/lib/jstl-1.1.2.jar,WEB-INF/lib/
 rome-0.9.jar,WEB-INF/lib/sitemesh-2.3.jar,WEB-INF/lib/slf4j-api-1.5.8
 .jar,WEB-INF/lib/slf4j-log4j12-1.5.8.jar,WEB-INF/lib/spring-2.5.6.jar
 ,WEB-INF/lib/spring-aop-2.5.6.jar,WEB-INF/lib/spring-beans-2.5.6.jar,
 WEB-INF/lib/spring-context-2.5.6.jar,WEB-INF/lib/spring-core-2.5.6.ja
 r,WEB-INF/lib/spring-tx-2.5.6.jar,WEB-INF/lib/spring-web-2.5.6.jar,WE
 B-INF/lib/standard-1.1.2.jar,WEB-INF/lib/stax-api-1.0-2.jar,WEB-INF/l
 ib/stax-api-1.0.1.jar
Built-By: hadrian
Tool: Bnd-0.0.313
Bundle-Name: mvn_org.apache.camel_camel-web_2.1.0_war
Created-By: 1.6.0_16 (Sun Microsystems Inc.)
WAR-URL: mvn:org.apache.camel/camel-web/2.1.0/war
Generated-By-Ops4j-Pax-From: mvn:org.apache.camel/camel-web/2.1.0/war
Build-Jdk: 1.5.0_20
Bundle-Version: 0
Bnd-LastModified: 1262961421375
Bundle-ManifestVersion: 2
Bundle-SymbolicName: mvn_org.apache.camel_camel-web_2.1.0_war
Import-Package: javax.accessibility;resolution:=optional,javax.annotat
 ion;resolution:=optional,javax.ejb;resolution:=optional,javax.el;reso
 lution:=optional,javax.faces.application;resolution:=optional,javax.f
 aces.context;resolution:=optional,javax.faces.el;resolution:=optional
 ,javax.faces.event;resolution:=optional,javax.interceptor;resolution:
 =optional,javax.jdo;resolution:=optional,javax.jdo.datastore;resoluti
 on:=optional,javax.jms;resolution:=optional,javax.jws;resolution:=opt
 ional,javax.mail;resolution:=optional,javax.mail.internet;resolution:
 =optional,javax.management;resolution:=optional,javax.management.mode
 lmbean;resolution:=optional,javax.management.openmbean;resolution:=op
 tional,javax.management.remote;resolution:=optional,javax.naming;reso
 lution:=optional,javax.naming.spi;resolution:=optional,javax.persiste
 nce;resolution:=optional,javax.persistence.spi;resolution:=optional,j
 avax.resource;resolution:=optional,javax.resource.cci;resolution:=opt
 ional,javax.resource.spi;resolution:=optional,javax.resource.spi.endp
 oint;resolution:=optional,javax.resource.spi.work;resolution:=optiona
 l,javax.rmi;resolution:=optional,javax.rmi.CORBA;resolution:=optional
 ,javax.script;resolution:=optional,javax.servlet;resolution:=optional
 ,javax.servlet.http;resolution:=optional,javax.servlet.jsp;resolution
 :=optional,javax.servlet.jsp.el;resolution:=optional,javax.servlet.js
 p.tagext;resolution:=optional,javax.sql;resolution:=optional,javax.sq
 l.rowset;resolution:=optional,javax.swing;resolution:=optional,javax.
 swing.border;resolution:=optional,javax.swing.event;resolution:=optio
 nal,javax.swing.plaf;resolution:=optional,javax.swing.plaf.basic;reso
 lution:=optional,javax.swing.plaf.metal;resolution:=optional,javax.sw
 ing.table;resolution:=optional,javax.swing.text;resolution:=optional,
 javax.swing.tree;resolution:=optional,javax.swing.undo;resolution:=op
 tional,javax.transaction;resolution:=optional,javax.transaction.xa;re
 solution:=optional,javax.ws.rs;resolution:=optional,javax.ws.rs.core;
 resolution:=optional,javax.ws.rs.ext;resolution:=optional,javax.xml.b
 ind;resolution:=optional,javax.xml.bind.annotation;resolution:=option
 al,javax.xml.bind.annotation.adapters;resolution:=optional,javax.xml.
 parsers;resolution:=optional,javax.xml.rpc;resolution:=optional,javax
 .xml.rpc.encoding;resolution:=optional,javax.xml.rpc.server;resolutio
 n:=optional,javax.xml.rpc.soap;resolution:=optional,javax.xml.soap;re
 solution:=optional,javax.xml.transform;resolution:=optional,javax.xml
 .transform.dom;resolution:=optional,javax.xml.transform.sax;resolutio
 n:=optional,javax.xml.transform.stream;resolution:=optional,javax.xml
 .validation;resolution:=optional,javax.xml.ws;resolution:=optional,ja
 vax.xml.ws.handler;resolution:=optional,javax.xml.ws.soap;resolution:
 =optional,javax.xml.xpath;resolution:=optional,org.w3c.dom;resolution
 :=optional,org.w3c.dom.traversal;resolution:=optional,org.xml.sax;res
 olution:=optional,org.xml.sax.ext;resolution:=optional,org.xml.sax.he
 lpers;resolution:=optional
Originally-Created-By: Apache Maven
Archiver-Version: Plexus Archiver
```

IT SEEMS THAT PAX KEEP INFO IN CACHE SOMEWHERE BECAUSE THE RESULT GENERATED CORRESPOND TO WHAT WAS DEFINED IN FIRST INSTALL

---

**Affects:** 1.1.2
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
Unless this is still a case (13 years have passed...), I'll close it @cmoulliard, ok?
