### ISSUE TITLE
The use of <mirrorOf>*</mirrorOf> in maven's settings.xml is ignored by aether. [PAXURL-288]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.url#318]
**[Jonathan Fortin](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:0b635e5a-4616-4ec5-a910-05e7d8933ee3)** created **[PAXURL-288](https://ops4j1.jira.com/browse/PAXURL-288)** 

The use of &lt;mirrorOf&gt;*&lt;/mirrorOf&gt; statement in the maven's settings.xml configuration file is ignored causing dependencies to not be downloaded.

We are running pax-exam tests with a karaf container. Dependencies resolved at run time to be downloaded by the aether resolver fail.

```
 2014-10-21 10:11:38,728 | WARN  | FelixStartLevel  | AetherBasedResolver              | 1 - org.ops4j.pax.url.mvn - 2.2.0 | Error resolving artifactorg.ops4j.pax.exam:pax-exam-features:xml:3.5.0:Could
 not find artifact org.ops4j.pax.exam:pax-exam-features:xml:3.5.0
shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.ops4j.pax.exam:pax-exam-features:xml:3.5.0
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:344)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolveFile(AetherBasedResolver.java:313)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:297)
        at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:131)
        at org.apache.karaf.features.internal.FeatureValidationUtil.load(FeatureValidationUtil.java:93)
        at org.apache.karaf.features.internal.FeatureValidationUtil.validate(FeatureValidationUtil.java:58)
        at org.apache.karaf.features.internal.FeaturesServiceImpl.validateRepository(FeaturesServiceImpl.java:162)
        at org.apache.karaf.features.internal.FeaturesServiceImpl.internalAddRepository(FeaturesServiceImpl.java:233)
        at org.apache.karaf.features.internal.FeaturesServiceImpl.initState(FeaturesServiceImpl.java:844)
        at org.apache.karaf.features.internal.FeaturesServiceImpl.start(FeaturesServiceImpl.java:856)
```

---

**Affects:** 2.2.0
Votes: 1, Watches: 3

**Comment by grgrzybek** [comment]
Works already, but I also reviewed it when upgrading Maven Resolver with #417
