### ISSUE TITLE
'assemblyref' Protocol not supported

### ISSUE THREAD

**Issue by ingmarkellner** [ops4j/org.ops4j.pax.url#389]
Hello,

I really like the Pax framework and evaluated it for our product development.
I followed the instructions on the wiki (https://ops4j1.jira.com/wiki/spaces/paxurl/pages/12648754/assembly+protocol) to use the assemblyref protocol, but always got a MalformedUrlException (see stacktrace below).

I finally noticed that the assemblyref classes are not included in the bundle and managed to get it working by adding the following line to the "Export-Package" section in pax-url-assembly/osgi.bnd:
${bundle.namespace}ref; version="${pom.version}"

Would be great if you include that fix in the next release. Thanks! (If you insist, I can of course also provide a pull request)

Stacktrace using version 2.6.7 of pax-url-assembly:
org.ops4j.pax.exam.TestContainerException: Problem starting test container.
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:212)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(EagerSingleStagedReactor.java:86)
	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(EagerSingleStagedReactor.java:136)
	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.java:457)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:97)
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.osgi.framework.BundleException: Error reading bundle content.
	at org.eclipse.osgi.storage.Storage.getContentConnection(Storage.java:619)
	at org.eclipse.osgi.storage.Storage.install(Storage.java:673)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:182)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:175)
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.installAndStartBundles(NativeTestContainer.java:340)
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:209)
	... 11 more
Caused by: java.net.MalformedURLException: unknown protocol: assemblyref
	at java.base/java.net.URL.<init>(URL.java:634)
	at java.base/java.net.URL.<init>(URL.java:523)
	at java.base/java.net.URL.<init>(URL.java:470)
	at org.eclipse.osgi.storage.Storage.createURL(Storage.java:669)
	at org.eclipse.osgi.storage.Storage.getContentConnection(Storage.java:649)
	at org.eclipse.osgi.storage.Storage.getContentConnection(Storage.java:615)
	... 16 more

**Comment by grgrzybek** [comment]
I never used pax-url-assembly, but I'd be happy to check your PR ;)

**Comment by ingmarkellner** [comment]
Created a pull request: https://github.com/ops4j/org.ops4j.pax.url/pull/390

**Comment by grgrzybek** [comment]
closed by #390
