### ISSUE TITLE
Is main buildable?

### ISSUE THREAD

**Issue by cstamas** [ops4j/org.ops4j.pax.url#421]
Note: when created issue I was trying to build master not main, mixed up as both exists...

I cannot make the build pass. Slowly pushing away obstacles, so far figured:
* to remove my own `~/.m2/settings.xml` (as some UTs asserts the local repo location, I intentionally use alt location)
* to use Java 8 as anything above seems to fail

But I still have 3 UT failures and 2 UT errors.

**Comment by cstamas** [comment]
Failures example:
*  AuthenticationTest.authenticationShouldFail 
Expected: (an instance of java.io.IOException and exception with message a string containing "Not authorized")
     but: exception with message a string containing "Not authorized" message was "Error resolving artifact ant:ant:jar:1.5.1: [Could not transfer artifact ant:ant:jar:1.5.1 from/to jetty-local (http://localhost:8778/): authentication failed for http://localhost:8778/ant/ant/1.5.1/ant-1.5.1.jar, status: 401 Unauthorized]"

Errors:
* HandlerTest.cacheTest:61 » IO Error resolving artifact org.ops4j.base:ops4j-ba...
* AetherTest.resolveArtifact:41 » IO Error resolving artifact org.ops4j.pax.web:...

**Comment by grgrzybek** [comment]
Let me check.

**Comment by grgrzybek** [comment]
Hmm
```
-                    <source>1.7</source>
-                    <target>1.7</target>
```
casued
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project pax-url-aether: Compilation failure: Compilation failure: 
[ERROR] /data/sources/github.com/ops4j/org.ops4j.pax.url/pax-url-aether/src/main/java/org/ops4j/pax/url/mvn/internal/config/MavenConfigurationImpl.java:[763,76] diamond operator is not supported in -source 1.6
[ERROR]   (use -source 7 or higher to enable diamond operator)
[ERROR] /data/sources/github.com/ops4j/org.ops4j.pax.url/pax-url-aether/src/main/java/org/ops4j/pax/url/mvn/internal/AetherBasedResolver.java:[624,61] diamond operator is not supported in -source 1.6
[ERROR]   (use -source 7 or higher to enable diamond operator)
[ERROR] /data/sources/github.com/ops4j/org.ops4j.pax.url/pax-url-aether/src/main/java/org/ops4j/pax/url/mvn/internal/AetherBasedResolver.java:[865,21] try-with-resources is not supported in -source 1.6
[ERROR]   (use -source 7 or higher to enable try-with-resources)
``` for me...

**Comment by cstamas** [comment]
wait a sec, which is the real? master or main? I worked again master, just to realize you have both

**Comment by grgrzybek** [comment]
`main` is the main ;)

**Comment by grgrzybek** [comment]
About maven-compiler-plugin it's strange, because `${maven.compiler.source}` should be enough to configure it...

**Comment by grgrzybek** [comment]
Works for me...
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OPS4J Pax Url 2.6.14-SNAPSHOT:
[INFO] 
[INFO] OPS4J Pax Url ...................................... SUCCESS [  0.355 s]
[INFO] OPS4J Pax Url - Commons ............................ SUCCESS [  1.419 s]
[INFO] OPS4J Pax Url - mvn: - support library ............. SUCCESS [  0.298 s]
[INFO] OPS4J Pax Url - mvn: ............................... SUCCESS [01:08 min]
[INFO] OPS4J Pax Url - assembly: .......................... SUCCESS [  0.703 s]
[INFO] OPS4J Pax Url - cache: ............................. SUCCESS [  0.354 s]
[INFO] OPS4J Pax Url - classpath: ......................... SUCCESS [  0.439 s]
[INFO] OPS4J Pax Url - dir: ............................... SUCCESS [  0.989 s]
[INFO] OPS4J Pax Url - link: .............................. SUCCESS [  0.321 s]
[INFO] OPS4J Pax Url - obr: ............................... SUCCESS [  0.252 s]
[INFO] OPS4J Pax Url - reference: ......................... SUCCESS [  0.365 s]
[INFO] OPS4J Pax Url - war: ............................... SUCCESS [  4.287 s]
[INFO] OPS4J Pax Url - wrap: .............................. SUCCESS [  1.646 s]
[INFO] OPS4J Pax Url - Integration Tests .................. SUCCESS [ 43.528 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:05 min
[INFO] Finished at: 2023-04-14T11:09:23+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by cstamas** [comment]
```
[INFO] Results :
[INFO] 
[INFO] Tests in error: 
[INFO]   MvnProtocolTest.installFromMvnUrl:79 » ArtifactResolution Error resolving arti...
[INFO] 
[INFO] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  7.691 s
[INFO] [INFO] Finished at: 2023-04-14T11:10:23+02:00
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Session stopped
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project itest-aether-osgi: There are test failures.
[INFO] [ERROR] 
[INFO] [ERROR] Please refer to /home/cstamas/Worx/ops4j/org.ops4j.pax.url/itest/target/it/aether-osgi-eclipse-3.7/target/surefire-reports for the individual test results.
[INFO] [ERROR] -> [Help 1]
[INFO] [ERROR] 
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[INFO]   The build exited with code 1. See /home/cstamas/Worx/ops4j/org.ops4j.pax.url/itest/target/it/aether-osgi-eclipse-3.7/build.log for details.
[INFO]           pom.xml .......................................... FAILED (8.8 s)
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OPS4J Pax Url 2.6.14-SNAPSHOT:
[INFO] 
[INFO] OPS4J Pax Url ...................................... SUCCESS [  0.196 s]
[INFO] OPS4J Pax Url - Commons ............................ SUCCESS [  0.967 s]
[INFO] OPS4J Pax Url - mvn: - support library ............. SUCCESS [  0.191 s]
[INFO] OPS4J Pax Url - mvn: ............................... SUCCESS [ 55.994 s]
[INFO] OPS4J Pax Url - assembly: .......................... SUCCESS [  0.623 s]
[INFO] OPS4J Pax Url - cache: ............................. SUCCESS [  0.260 s]
[INFO] OPS4J Pax Url - classpath: ......................... SUCCESS [  0.364 s]
[INFO] OPS4J Pax Url - dir: ............................... SUCCESS [  1.151 s]
[INFO] OPS4J Pax Url - link: .............................. SUCCESS [  0.299 s]
[INFO] OPS4J Pax Url - obr: ............................... SUCCESS [  0.412 s]
[INFO] OPS4J Pax Url - reference: ......................... SUCCESS [  0.301 s]
[INFO] OPS4J Pax Url - war: ............................... SUCCESS [  7.171 s]
[INFO] OPS4J Pax Url - wrap: .............................. SUCCESS [  1.338 s]
[INFO] OPS4J Pax Url - Integration Tests .................. FAILURE [ 36.423 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:46 min
[INFO] Finished at: 2023-04-14T11:10:23+02:00
[INFO] ------------------------------------------------------------------------
[INFO] Session stopped
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.5.1:run (aether-osgi-eclipse-3.7) on project itest: 1 build failed. See console output above for details. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :itest
[cstamas@urnebes org.ops4j.pax.url (main)]$ 
```

**Comment by grgrzybek** [comment]
Ah wait, I've `@Ignore`d the test in e8cb6ccdfd0c40b2ef1e182f8fe181eb87cabec5...

**Comment by grgrzybek** [comment]
`itest/target/it/aether-osgi-eclipse-3.7/target/surefire-reports/org.ops4j.pax.url.itest.mvn.osgi.MvnProtocolTest.txt`:
```
-------------------------------------------------------------------------------
Test set: org.ops4j.pax.url.itest.mvn.osgi.MvnProtocolTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.434 sec - in org.ops4j.pax.url.itest.mvn.osgi.MvnProtocolTest
```
May I see yours?

**Comment by cstamas** [comment]
```
-------------------------------------------------------------------------------
Test set: org.ops4j.pax.url.itest.mvn.osgi.MvnProtocolTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.771 sec <<< FAILURE! - in org.ops4j.pax.url.itest.mvn.osgi.MvnProtocolTest
installFromMvnUrl(org.ops4j.pax.url.itest.mvn.osgi.MvnProtocolTest)  Time elapsed: 0.768 sec  <<< ERROR!
shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.ops4j.base:ops4j-base-lang:jar:1.0.0
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:431)
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:235)
        at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:212)
        at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:272)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
        at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:555)
        at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:123)
        at java.net.URL.openStream(URL.java:1093)
        at org.ops4j.pax.url.itest.mvn.osgi.MvnProtocolTest.installFromMvnUrl(MvnProtocolTest.java:79)
```

But in build.log: `Caused by: java.net.UnknownHostException: repo1.maven.org: Name or service not known`

Seems I had a network brownout during build... rebuilding

**Comment by cstamas** [comment]
All fine now, closing the issue:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OPS4J Pax Url 2.6.14-SNAPSHOT:
[INFO] 
[INFO] OPS4J Pax Url ...................................... SUCCESS [  0.192 s]
[INFO] OPS4J Pax Url - Commons ............................ SUCCESS [  0.943 s]
[INFO] OPS4J Pax Url - mvn: - support library ............. SUCCESS [  0.187 s]
[INFO] OPS4J Pax Url - mvn: ............................... SUCCESS [ 52.687 s]
[INFO] OPS4J Pax Url - assembly: .......................... SUCCESS [  0.545 s]
[INFO] OPS4J Pax Url - cache: ............................. SUCCESS [  0.261 s]
[INFO] OPS4J Pax Url - classpath: ......................... SUCCESS [  0.327 s]
[INFO] OPS4J Pax Url - dir: ............................... SUCCESS [  0.821 s]
[INFO] OPS4J Pax Url - link: .............................. SUCCESS [  0.263 s]
[INFO] OPS4J Pax Url - obr: ............................... SUCCESS [  0.169 s]
[INFO] OPS4J Pax Url - reference: ......................... SUCCESS [  0.271 s]
[INFO] OPS4J Pax Url - war: ............................... SUCCESS [  3.161 s]
[INFO] OPS4J Pax Url - wrap: .............................. SUCCESS [  1.330 s]
[INFO] OPS4J Pax Url - Integration Tests .................. SUCCESS [ 32.287 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:34 min
[INFO] Finished at: 2023-04-14T11:22:09+02:00
[INFO] ------------------------------------------------------------------------
[INFO] Session stopped
[cstamas@urnebes org.ops4j.pax.url (main)]$ 

```
